version: '2'
services:
  node1:
    build: ./server
    container_name: node1
    ports:
      - 3000:3000
    restart: always
  node2:
    build: ./server
    container_name: node2
    ports:
      - 3001:3000
    restart: always
  node3:
    build: ./server
    container_name: node3
    ports:
      - 3002:3000
    restart: always
  node4:
    build: ./server
    container_name: node4
    ports:
      - 3003:3000
    restart: always
  agent:
    build: ../../ # shaunw321/node-container-agent
    container_name: node_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/var/log/nodeagent
